[project]
name = "GooseCasinoSim"
version = "0.1.0"
description = "Simulation with user-defined collections and pseudo-random model"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
